### ISSUE TITLE
Opening from filesystem produces error on branch

### ISSUE THREAD

**Issue by am-cornelis** [sgmap/cout-embauche#256]
Hello,

An error appears on the page when we open `index.html` directly from the file system (i.e. without serving it), on the `advanced` branch. It works fine on the `gh-pages` branch.

Details:
I cloned this repository, then opened the `index.html` in Chrome (`file:///D:/src/cout-embauche/index.html`). The application behaved correctly: typing in numbers in the input produced a number in the output.
I switched to the `advanced` branch, reloaded the page and received the following error:

```
Merci d'envoyer un rapport d'erreur contenant les informations ci-dessous pour améliorer le simulateur !

Détails techniques :

Error: Bad Request
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
```

I also tried opening the file in Edge, and got the same error.

Attached is the result, with the console.
![cout-embauche_network-error](https://cloud.githubusercontent.com/assets/517959/19808517/2953bea4-9d1d-11e6-8ba8-9ec661976243.png)

**Comment by am-cornelis** [comment]
By the way: it works fine when following instructions and starting the webpack dev server to actually server the file on http://localhost:3000. I just wanted to highlight the change of behaviour between the main branch and this one...

**Comment by laem** [comment]
Hi,
Thanks for your interest. Your error is due to the fact that the code displayed in your browser is a very old one : it is the latest compiled version.  Running `npm install` then `npm start`, and opening your browser to `http://localhost:3000` should show you the latest development version (not necessarily stable...). 
The `advanced` branch is a development branch. The docs have not been updated yet to explain how to run it for development or for production, sorry about that. A new page will also explain how to integrate the widget in a host website (probably using an iframe now). This should happen in november :smiley:

**Comment by laem** [comment]
The new code is now on the `master` branch, and the README was updated
